---
name: run-build-test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Run NPM builds
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: debug
        run: ls -la

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Build dist
        run: npm run build

      - name: test
        run: ls -la dist/
